### ISSUE TITLE
app goes blank with rollupify

### ISSUE THREAD

**Issue by threepointone** [nolanlawson/rollupify#18]
Hi, I'm trying to get rollupify into react-css, but simply enabling the transform gives me a blank app. [I have a branch to reproduce this](https://github.com/threepointone/react-css/tree/rollup) - the commit right before HEAD shows rectangles on the screen; after the last commit, which is just to add the transform, the screen goes blank, no errors either. am I doing something wrong? you can reproduce with `npm install && npm start`, and opening `http://localhost:9966` if you'd like. I'll investigate some more, but not sure what to look for yet. Please and thank you!

**Comment by threepointone** [comment]
following up - It fails because I have jsx (and other babel goodies) in my js; but the readme clearly says to put rollupify before babelify. if I put this after, I see it works, but none of the es6 module goodness (because babel converts it to commonjs?). not sure how to workaround this.

**Comment by threepointone** [comment]
I made some progress, had to rewrite some code too, but now react's broken 

<img width="447" alt="screen shot 2016-07-25 at 5 55 41 pm" src="https://cloud.githubusercontent.com/assets/18808/17101262/390caecc-5291-11e6-8ef0-df0c864c725c.png">

I'll get back to this later I think

**Comment by threepointone** [comment]
scratch that, look like the react-hot-loader beta has issues with rollup, I'll investigate that separately. I think the README is misleading, you can't get rollupify to work with babelify, you need to use rollup's babel plugin for the same (via twitter - https://twitter.com/Rich_Harris/status/757536445473099776)

Thank you!

**Comment by nolanlawson** [comment]
Sorry about that; I had success using babelify with rollupify, but I don't use JSX so that may be why. Sorry you ran into so many issues; thanks for the explanation!

**Comment by threepointone** [comment]
would you like a PR for the documentation? I'll change the base example to another transform, and add a subsection specifically for Babel. I could add a note about errorify too.

**Comment by nolanlawson** [comment]
Yes please, that would be helpful. :)

**Comment by hiddentao** [comment]
Glad I saw this issue. Am about to try and get this working myself - if I do I'll raise a PR for updating the README.
