### ISSUE TITLE
Any way to make this play nicely with require()?

### ISSUE THREAD

**Issue by brandonros** [nolanlawson/rollupify#23]
I read the article about the performance benefits, but I have 0 ES2015 code and a lot of `require()`s.

Any insight would be highly appreciated. :)

**Comment by nolanlawson** [comment]
Have you looked at [cjs-to-es6](https://github.com/nolanlawson/cjs-to-es6)? It's not perfect, but it can get you started.

**Comment by brandonros** [comment]
@nolanlawson Thanks for that.

One hiccup:

```
var error = module.exports;

error.handle = function (err) {
...
};

error.something_else = function (err) {
...
};
```

`>> Error: Module error.js does not export default`

I have a ton of files written like this. How can I craftily replace it and what should I be replacing it to?

**Comment by brandonros** [comment]
Solved that with a little find and replace.

Now `Module address.js does not export format`

```
var address_module = {};

export default address_module;

address_module.foo = function () {...};
```

**Comment by brandonros** [comment]
Got that one.

`import {format as format_address} from './address.js';`

That was nasty.

Sorry, I am putting this here in hopes it helps somebody else.

Up  next: `>> Error: Cannot find module './notification.js' from ''.` (which sounds easy but didn't happen before when I was using require...

**Comment by brandonros** [comment]
Ok. That one was because cjs-to-es6 didn't hit every file due to transformation errors.

What's the right way to write:

```
module.exports = {
a: 'b',
c: 'd'
};
```

as an ES6 module, export wise?

**Comment by nolanlawson** [comment]
``` js
// foo.js
var a = 'b'
var c = 'd'
export { a, c }
```

Then elsewhere:

``` js
import { a } from './foo'
```
