### ISSUE TITLE
Pass CLI options into Rollup

### ISSUE THREAD

**Issue by rafaelrinaldi** [nolanlawson/rollupify#3]
I'm trying to minify my final bundle and found [this tiny plugin](https://github.com/TrySound/rollup-plugin-uglify) that seems to do the job. However, it seems that `rollupify` is bypassing the CLI options.

This is my current command:

```
$ browserify source/scripts -t [ rollupify --plugins [ rollup-plugin-uglify ]  ] -t [ babelify --presets [ es2015 ] ] -do public/bundle.js
```

Am I doing something wrong?

**Comment by nolanlawson** [comment]
`rollupify` does not currently accept any CLI option. PRs welcome! :)

**Comment by rafaelrinaldi** [comment]
@nolanlawson I will give it a try!
