### ISSUE TITLE
why is `opts.sourceMaps`?

### ISSUE THREAD

**Issue by tunnckoCore** [nolanlawson/rollupify#48]
Hell yea, I think I finally got great combo with browserify and rollupify :)

But looking at the code, I don't understand and don't like that `opts.sourceMaps` thing. Rollup gets `sourceMap` option. Why not just let Object.assign do its job.

I mean, just remove 
```js
var doSourceMap = opts.sourceMaps !== false;
```

and change to 

```js
      return rollup.rollup(Object.assign(config, opts.config || opts, {
        cache: cache,
        entry: tmpfile
      }))
```

it won't force you to pass sourceMap**s**, when you have it from rollup config

edit: just don't see sense to override config (the sourceMap prop)

**Comment by nolanlawson** [comment]
I honestly can't recall why I did that. You're right I should probably just pass the `sourceMap` value through, but it would be a breaking change.

**Comment by nolanlawson** [comment]
Closing stale issues
