### ISSUE TITLE
watchify + rollupify generates a weird warning when using a dependency in node_modules

### ISSUE THREAD

**Issue by DavidBruant** [nolanlawson/rollupify#53]
Example repo : https://github.com/DavidBruant/rollupify-bug-example

In this repo, I have this:

````
$ npm run watch-roll

> rollupify-bug-example@1.0.0 watch-roll /home/david/projects/rollupify-bug-example
> watchify main.js -t rollupify -o bundle-rollup.js -d -v

'lodash.memoize' is imported by main.js.tmp, but could not be resolved – treating it as an external dependency
47294 bytes written to bundle-rollup.js (0.34 seconds) at 16:59:38
````

This warning ("but could not be resolved") does not exist when I try to compile with babelify for instance.

**Comment by benmcp** [comment]
Any update on this? I can't seem to import/bundle external node_modules packages.

What am I missing here?

**Comment by nolanlawson** [comment]
Thanks very much for the repro. Rollupify assumes that your `import`s are CommonJS (usually third-party) and ignores them, passing them on to Browserify. In this example you're `import`ing `lodash.memoize` which is a CommonJS module, and hence Rollup is confused about it. The fix would be to change the `import` to `require()`.
