### ISSUE TITLE
Rollup errors not propagated to browserify

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/rollupify#9]
Noticed this during development; rollup errors are silent failures.

**Comment by dariocravero** [comment]
I meant to raise this for a while and totally forgot. Good you brought it
up :). It also hangs watchify when rollup fails. I tried a few things but
they didn't work (mainly around how Promises are handled) and didn't have
time to try again yet.

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/rollupify/pull/10
